spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: MESADEAYUDA
    password: mesa32
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
