@startuml
skinparam backgroundColor #FFFFFF
skinparam activity {
  StartColor #7B1E3D
  EndColor #7B1E3D
  BackgroundColor #F9F5F3
  BorderColor #B48954
  FontColor #7B1E3D
}

start

:Servidor Público accede al módulo\n"Solicitud de Soporte";
:Completa formulario de solicitud;
:Envía solicitud;

:Sistema genera ticket en PDF;
:Sistema registra ticket;
:Estado inicial = "Pendiente";


:Ticket aparece en el dashboard del Administrador;

if (Administrador revisa ticket?) then (Sí)
  :Administrador analiza la solicitud;
  :Asigna técnico responsable;
  :Estado cambia a "Asignado";

  :Ticket aparece en bandeja del Técnico;
  :Técnico consulta tickets asignados;
  :Técnico visualiza detalle del ticket;
  :Técnico asume el ticket;
  :Estado cambia a "En proceso";

  :Técnico atiende la solicitud;


  if (Servicio completado?) then (Sí)
    :Técnico finaliza atención;
    :Estado cambia a "Finalizado";
    :Servidor Público firma\ncumplimiento del servicio;
    :Administrador valida el cumplimiento del ticket en el dashboard;
    :Ticket se registra en\nbitácora histórica;
  else (No)
    :Administrador reasigna\na otro técnico;
    :Estado permanece "Asignado";
  endif

else (No)
  :Ticket permanece\ncon estado "Pendiente";
endif

stop
@enduml
